title: Pullreview Documentations
email: support@pullreview.com
description: "PullReview Documentations."

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title

gems:
  - jekyll-sitemap